name: imarket
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4 # أُضيفت من A (الباكج الأساسي للـ bloc)

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.1

  webview_flutter_web: ^0.2.2

  # Value Equality
  equatable: ^2.0.7

  # Supabase & Backend
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^6.0.0

  # UI & Utilities
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  photo_view: ^0.15.0
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  
  # Device & Permissions
  image_picker: ^1.2.0
  media_store_plus: ^0.1.3   
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  dio: ^5.9.0
  webview_flutter: ^4.13.0
  http: ^1.5.0
  flutter_staggered_animations: ^1.1.1

  # Navigation
  go_router: ^16.2.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Functional Programming
  dartz: ^0.10.1

  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  # Others
  provider: ^6.1.5+1
  shimmer: ^3.0.0 
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  hive_generator: ^2.0.1

  # Code Generation for DI
  injectable_generator: ^2.4.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Regular.ttf
        - asset: fonts/Tajawal-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  remove_alpha_ios: true
